"""Study 3R tokenizer-only acquisition and interface-surface probe.

Authority: ``studies/study3r/prompts/study3r_protocol_v1_authoring_authority.md``

This module performs the *only* network and tokenizer operations authorized in
the Study 3R protocol-authoring session:

* resolve one immutable revision SHA for the target checkpoint ``RT`` and for
  each of the three registered RP-B ladder candidates;
* download an explicit allow-list of metadata and tokenizer files at those
  revisions;
* instantiate each tokenizer with ``trust_remote_code=False``;
* freeze the E0 legal answer surfaces, the D0 candidate surfaces, both E0
  wrapper arms and the canonical generated-CoT route as bytes and token IDs;
* emit a sealed acquisition record and a tokenizer functional-equivalence
  record classifying isomorphic re-instantiation strata.

It never downloads a weight file, never constructs a model, never runs a
forward pass, never reads a logit, never scores a candidate and never generates
a token. Every such counter is emitted as an explicit zero.
"""

from __future__ import annotations

import argparse
import datetime as _datetime
import hashlib
import json
import os
import pathlib
import platform
import sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
ACQUISITION_DIR = ROOT / "studies" / "study3r" / "acquisition"

sys.path.insert(0, str(ROOT / "studies" / "study3r" / "tasks"))

import study3r_task_generators_v1 as tasks  # noqa: E402

# ---------------------------------------------------------------------------
# Registered study roles
# ---------------------------------------------------------------------------

TARGET_CHECKPOINT = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"

#: Fixed membership and fixed order, L = 3. No fallback, no substitution, no
#: reordering, no post-result expansion.
RP_B_LADDER = (
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
)

CHECKPOINT_ROLES = (
    ("RT", TARGET_CHECKPOINT),
    ("RP_B1", RP_B_LADDER[0]),
    ("RP_B2", RP_B_LADDER[1]),
    ("RP_B3", RP_B_LADDER[2]),
)

#: The explicit download allow-list. Nothing outside this tuple is fetched.
DOWNLOAD_ALLOW_LIST = (
    "config.json",
    "generation_config.json",
    "tokenizer_config.json",
    "tokenizer.json",
)

#: Any repository path matching one of these suffixes is a weight-bearing file
#: and is provably never requested.
WEIGHT_SUFFIXES = (
    ".safetensors", ".bin", ".pt", ".pth", ".ckpt", ".h5", ".msgpack",
    ".gguf", ".onnx", ".npz", ".pkl",
)

# ---------------------------------------------------------------------------
# Registered interface identifiers and envelope rules
# ---------------------------------------------------------------------------

RAW_ARM_ID = "W1_RAW_DIRECT"
CHAT_ARM_ID = "W2_ROLE_CANONICAL"
COT_ROUTE_ID = "C1_CANONICAL_GENERATED_COT"

#: The single field that differs between the two matched E0 arms.
ARM_DIFFERENTIATING_FIELD = "envelope"

#: Reasoning-span markers. If a checkpoint's role-canonical generation prompt
#: ends by *opening* a reasoning span, the role-canonical arm closes that span
#: with frozen bytes so that E0 still measures zero *generated* reasoning
#: tokens. The closure is given by the wrapper, never generated by the model.
REASONING_OPEN_MARKERS = ("<think>", "<think>\n", "<think>\n\n")
REASONING_CLOSE_BYTES = "</think>\n\n"

#: The canonical generated-CoT instruction. It is separate from E0 by
#: construction and never shares an envelope with an E0 arm.
COT_INSTRUCTION = (
    "Reason step by step. Finish with a final line of exactly the form\n"
    "Final answer: X\n"
    "where X is exactly one option label."
)

#: The frozen generated-CoT parser, applied to the decoded generation.
COT_PARSER_ID = "P1_FINAL_ANSWER_LAST_LINE"
COT_PARSER_REGEX = r"^Final answer: ([ABCD])$"

#: E0 termination margin, in tokens, added to the longest legal answer surface.
E0_TERMINATION_MARGIN_TOKENS = 1


class Study3RAcquisitionError(RuntimeError):
    """Raised when a fixed checkpoint or tokenizer artifact cannot be resolved."""


COUNTERS = {
    "network_metadata_requests": 0,
    "network_file_downloads": 0,
    "files_acquired": 0,
    "tokenizer_constructions": 0,
    "encode_calls": 0,
    "decode_calls": 0,
    "chat_template_renders": 0,
    "weight_files_acquired": 0,
    "model_constructions": 0,
    "forward_passes": 0,
    "prefill_operations": 0,
    "logit_reads": 0,
    "scoring_operations": 0,
    "generations": 0,
    "gpu_or_cloud_jobs": 0,
    "remote_code_executions": 0,
    "scientific_items_realized": 0,
    "execution_seeds_drawn": 0,
    "interfaces_selected": 0,
    "evidence_ledger_rows_written": 0,
}

NETWORK_LOG = []


def _sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _sha256_text(text: str) -> str:
    return _sha256_bytes(text.encode("utf-8"))


def write_json(path: pathlib.Path, payload) -> None:
    """Deterministic, ASCII-safe, LF-only JSON serialisation."""
    path.parent.mkdir(parents=True, exist_ok=True)
    rendered = json.dumps(payload, indent=1, sort_keys=True,
                          ensure_ascii=True) + "\n"
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(rendered)


# ---------------------------------------------------------------------------
# Acquisition
# ---------------------------------------------------------------------------


def resolve_and_download(repo_id: str, cache_root: pathlib.Path):
    """Resolve the immutable revision and fetch the allow-listed files only."""
    from huggingface_hub import HfApi, hf_hub_download

    api = HfApi()
    COUNTERS["network_metadata_requests"] += 1
    NETWORK_LOG.append({
        "kind": "metadata",
        "method": "GET",
        "url": "https://huggingface.co/api/models/%s" % repo_id,
    })
    try:
        info = api.model_info(repo_id=repo_id, files_metadata=False)
    except Exception as error:  # pragma: no cover - network failure path
        raise Study3RAcquisitionError(
            "STUDY3R_PROTOCOL_AUTHORING_FAILED_CHECKPOINT_OR_TOKENIZER_UNRESOLVABLE: "
            "%s: %s" % (repo_id, error))
    revision = getattr(info, "sha", None)
    if not revision or len(revision) != 40:
        raise Study3RAcquisitionError(
            "STUDY3R_PROTOCOL_AUTHORING_FAILED_CHECKPOINT_OR_TOKENIZER_UNRESOLVABLE: "
            "%s has no immutable revision" % repo_id)

    repository_paths = sorted(sibling.rfilename for sibling in info.siblings)
    weight_paths = sorted(path for path in repository_paths
                          if path.lower().endswith(WEIGHT_SUFFIXES))

    local_dir = cache_root / repo_id.replace("/", "__") / revision
    local_dir.mkdir(parents=True, exist_ok=True)

    acquired = []
    for relative in DOWNLOAD_ALLOW_LIST:
        if relative not in repository_paths:
            if relative == "generation_config.json":
                continue
            raise Study3RAcquisitionError(
                "STUDY3R_PROTOCOL_AUTHORING_FAILED_CHECKPOINT_OR_TOKENIZER_UNRESOLVABLE: "
                "%s@%s is missing %s" % (repo_id, revision, relative))
        COUNTERS["network_file_downloads"] += 1
        NETWORK_LOG.append({
            "kind": "file",
            "method": "GET",
            "url": "https://huggingface.co/%s/resolve/%s/%s"
                   % (repo_id, revision, relative),
        })
        fetched = hf_hub_download(repo_id=repo_id, filename=relative,
                                  revision=revision,
                                  local_dir=str(local_dir))
        payload = pathlib.Path(fetched).read_bytes()
        if relative.lower().endswith(WEIGHT_SUFFIXES):  # pragma: no cover
            COUNTERS["weight_files_acquired"] += 1
        COUNTERS["files_acquired"] += 1
        acquired.append({
            "path": relative,
            "bytes": len(payload),
            "sha256": _sha256_bytes(payload),
        })

    on_disk = sorted(str(child.relative_to(local_dir)).replace(os.sep, "/")
                     for child in local_dir.rglob("*")
                     if child.is_file() and ".cache" not in child.parts)
    stray = [path for path in on_disk if path.lower().endswith(WEIGHT_SUFFIXES)]
    if stray:  # pragma: no cover - defensive
        raise Study3RAcquisitionError("weight file present on disk: %r" % stray)

    return {
        "repository_id": repo_id,
        "immutable_revision": revision,
        "download_allow_list": list(DOWNLOAD_ALLOW_LIST),
        "acquired_files": acquired,
        "local_paths_on_disk": on_disk,
        "repository_paths_at_revision": repository_paths,
        "weight_paths_present_in_repository": weight_paths,
        "weight_paths_requested": [],
        "weight_bytes_acquired": 0,
        "local_dir": str(local_dir),
    }


# ---------------------------------------------------------------------------
# Tokenizer surfaces
# ---------------------------------------------------------------------------


def _encode(tokenizer, text: str):
    COUNTERS["encode_calls"] += 1
    return list(tokenizer(text, add_special_tokens=False)["input_ids"])


def _surface(tokenizer, text: str):
    ids = _encode(tokenizer, text)
    payload = text.encode("utf-8")
    return {
        "text": text,
        "utf8_bytes": len(payload),
        "utf8_sha256": _sha256_bytes(payload),
        "token_ids": ids,
        "token_count": len(ids),
    }


def _common_prefix_length(sequences):
    if not sequences:
        return 0
    shortest = min(len(sequence) for sequence in sequences)
    for index in range(shortest):
        column = {sequence[index] for sequence in sequences}
        if len(column) != 1:
            return index
    return shortest


def probe_checkpoint(role: str, record, cache_root: pathlib.Path):
    """Freeze every byte/token surface for one checkpoint revision."""
    from transformers import AutoTokenizer

    local_dir = record["local_dir"]
    try:
        tokenizer = AutoTokenizer.from_pretrained(
            local_dir, trust_remote_code=False, use_fast=True)
    except Exception as error:
        raise Study3RAcquisitionError(
            "STUDY3R_PROTOCOL_AUTHORING_FAILED_CHECKPOINT_OR_TOKENIZER_UNRESOLVABLE: "
            "%s could not be instantiated with trust_remote_code=False: %s"
            % (record["repository_id"], error))
    COUNTERS["tokenizer_constructions"] += 1

    config = json.loads((pathlib.Path(local_dir) / "config.json").read_text(
        encoding="utf-8"))
    tokenizer_config = json.loads(
        (pathlib.Path(local_dir) / "tokenizer_config.json").read_text(
            encoding="utf-8"))
    generation_config_path = pathlib.Path(local_dir) / "generation_config.json"
    generation_config = (
        json.loads(generation_config_path.read_text(encoding="utf-8"))
        if generation_config_path.exists() else {})

    chat_template = tokenizer_config.get("chat_template")
    if not isinstance(chat_template, str) or not chat_template:
        raise Study3RAcquisitionError(
            "STUDY3R_PROTOCOL_AUTHORING_FAILED_CHECKPOINT_OR_TOKENIZER_UNRESOLVABLE: "
            "%s exposes no chat template" % (record["repository_id"],))

    # Legal E0 answer surfaces.
    answer_surfaces = {label: _surface(tokenizer, label)
                       for label in tasks.LABELS}
    longest_surface_tokens = max(surface["token_count"]
                                 for surface in answer_surfaces.values())
    max_new_tokens = longest_surface_tokens + E0_TERMINATION_MARGIN_TOKENS

    fixture = tasks.canonical_fixture()
    item_body = str(fixture["item_body"])

    # Arm 1: common raw/direct-answer envelope, identical bytes everywhere.
    raw_prompt = tasks.raw_arm_prompt(item_body)

    # Arm 2: checkpoint-revision-specific role-canonical envelope.
    COUNTERS["chat_template_renders"] += 1
    chat_prefix = tokenizer.apply_chat_template(
        [{"role": "user", "content": item_body}],
        tokenize=False, add_generation_prompt=True)
    opened = [marker for marker in REASONING_OPEN_MARKERS
              if chat_prefix.endswith(marker)]
    reasoning_span_opened = bool(opened)
    closure = REASONING_CLOSE_BYTES if reasoning_span_opened else ""
    chat_prompt = chat_prefix + closure + tasks.ANSWER_CUE

    # Canonical generated-CoT route: separate envelope, separate parser.
    COUNTERS["chat_template_renders"] += 1
    cot_prompt = tokenizer.apply_chat_template(
        [{"role": "user", "content": item_body + "\n\n" + COT_INSTRUCTION}],
        tokenize=False, add_generation_prompt=True)

    arms = {}
    for arm_id, prompt in ((RAW_ARM_ID, raw_prompt),
                           (CHAT_ARM_ID, chat_prompt)):
        prompt_surface = _surface(tokenizer, prompt)
        candidates = {}
        full_sequences = []
        for label in tasks.LABELS:
            ids = prompt_surface["token_ids"] + answer_surfaces[label]["token_ids"]
            full_sequences.append(ids)
            candidates[label] = {
                "candidate_text": prompt + label,
                "candidate_token_ids": ids,
                "candidate_token_count": len(ids),
            }
        prefix_length = _common_prefix_length(full_sequences)
        arms[arm_id] = {
            "arm_id": arm_id,
            "prompt": prompt_surface,
            "d0_candidates": candidates,
            "d0_common_prefix_token_length": prefix_length,
            "d0_common_prefix_token_ids":
                full_sequences[0][:prefix_length],
            "d0_discriminant_position": prefix_length,
            "d0_discriminant_token_ids": {
                label: full_sequences[index][prefix_length]
                for index, label in enumerate(tasks.LABELS)
            },
        }

    eos_token = tokenizer_config.get("eos_token")
    if isinstance(eos_token, dict):
        eos_token = eos_token.get("content")

    return {
        "role": role,
        "repository_id": record["repository_id"],
        "immutable_revision": record["immutable_revision"],
        "tokenizer_class": type(tokenizer).__name__,
        "vocab_size_from_config": config.get("vocab_size"),
        "tokenizer_vocab_size": int(tokenizer.vocab_size),
        "max_position_embeddings": config.get("max_position_embeddings"),
        "model_type": config.get("model_type"),
        "trust_remote_code": False,
        "special_tokens": {
            "bos_token": tokenizer.bos_token,
            "bos_token_id": tokenizer.bos_token_id,
            "eos_token": tokenizer.eos_token,
            "eos_token_id": tokenizer.eos_token_id,
            "pad_token": tokenizer.pad_token,
            "pad_token_id": tokenizer.pad_token_id,
            "unk_token": tokenizer.unk_token,
            "tokenizer_config_eos_token": eos_token,
            "generation_config_eos_token_id":
                generation_config.get("eos_token_id"),
            "generation_config_bos_token_id":
                generation_config.get("bos_token_id"),
        },
        "chat_template_sha256": _sha256_text(chat_template),
        "chat_template_bytes": len(chat_template.encode("utf-8")),
        "e0": {
            "legal_answer_surfaces": answer_surfaces,
            "longest_legal_answer_surface_tokens": longest_surface_tokens,
            "termination_margin_tokens": E0_TERMINATION_MARGIN_TOKENS,
            "max_new_tokens": max_new_tokens,
            "add_special_tokens": False,
            "do_sample": False,
        },
        "arms": arms,
        "role_canonical_envelope": {
            "generation_prompt": _surface(tokenizer, chat_prefix),
            "reasoning_span_opened_by_template": reasoning_span_opened,
            "reasoning_open_marker": opened[0] if opened else None,
            "frozen_reasoning_closure": closure,
            "answer_cue": tasks.ANSWER_CUE,
        },
        "cot_route": {
            "route_id": COT_ROUTE_ID,
            "instruction": COT_INSTRUCTION,
            "prompt": _surface(tokenizer, cot_prompt),
            "parser_id": COT_PARSER_ID,
            "parser_regex": COT_PARSER_REGEX,
            "k": 1,
            "do_sample": False,
        },
        "acquired_file_hashes": {entry["path"]: entry["sha256"]
                                 for entry in record["acquired_files"]},
    }


# ---------------------------------------------------------------------------
# Functional equivalence and isomorphic re-instantiation strata
# ---------------------------------------------------------------------------


def equivalence_tuple(probe, arm_id: str):
    """The ``(bytes, token IDs, common prefix, discriminant position)`` tuple."""
    arm = probe["arms"][arm_id]
    return {
        "bytes": arm["prompt"]["utf8_sha256"],
        "token_ids": arm["prompt"]["token_ids"],
        "common_prefix": arm["d0_common_prefix_token_ids"],
        "discriminant_position": arm["d0_discriminant_position"],
        "answer_surface_token_ids": {
            label: probe["e0"]["legal_answer_surfaces"][label]["token_ids"]
            for label in tasks.LABELS
        },
    }


def build_equivalence(probes):
    reference = probes[0]
    strata = {}
    comparisons = []
    for arm_id in (RAW_ARM_ID, CHAT_ARM_ID):
        reference_tuple = equivalence_tuple(reference, arm_id)
        for probe in probes:
            candidate = equivalence_tuple(probe, arm_id)
            differing = sorted(key for key in reference_tuple
                               if reference_tuple[key] != candidate[key])
            comparisons.append({
                "arm_id": arm_id,
                "reference_role": reference["role"],
                "role": probe["role"],
                "repository_id": probe["repository_id"],
                "immutable_revision": probe["immutable_revision"],
                "identical_to_reference": not differing,
                "differing_tuple_elements": differing,
            })
    for probe in probes:
        signature = hashlib.sha256(json.dumps(
            {arm_id: equivalence_tuple(probe, arm_id)
             for arm_id in (RAW_ARM_ID, CHAT_ARM_ID)},
            sort_keys=True).encode("utf-8")).hexdigest()
        strata.setdefault(signature, []).append(probe["role"])
    stratum_ids = {}
    for index, signature in enumerate(sorted(strata), start=1):
        stratum_ids[signature] = "STRATUM_%02d" % index
    return {
        "reference_role": reference["role"],
        "verified_tuple_elements": ["bytes", "token_ids", "common_prefix",
                                    "discriminant_position",
                                    "answer_surface_token_ids"],
        "comparisons": comparisons,
        "strata": sorted(
            ({"stratum_id": stratum_ids[signature],
              "signature_sha256": signature,
              "roles": sorted(roles)}
             for signature, roles in strata.items()),
            key=lambda entry: entry["stratum_id"]),
        "role_to_stratum": {
            role: stratum_ids[signature]
            for signature, roles in strata.items() for role in roles},
        "pooling_rule": (
            "A checkpoint whose (bytes, token IDs, common prefix, discriminant "
            "position) tuple differs from the reference in any element is an "
            "isomorphic re-instantiation stratum and is never pooled as the "
            "same frozen byte/token interface."),
        "distinct_stratum_count": len(strata),
    }


# ---------------------------------------------------------------------------
# Schemas for the sealed acquisition artifacts
# ---------------------------------------------------------------------------

SHA256_PATTERN = r"^[0-9a-f]{64}$"
REVISION_PATTERN = r"^[0-9a-f]{40}$"

_REPOSITORY_IDS = [TARGET_CHECKPOINT] + list(RP_B_LADDER)
_ROLE_IDS = [role for role, _ in CHECKPOINT_ROLES]


def _surface_schema(min_tokens: int = 1):
    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["text", "token_count", "token_ids", "utf8_bytes",
                     "utf8_sha256"],
        "properties": {
            "text": {"type": "string", "minLength": 1},
            "utf8_bytes": {"type": "integer", "minimum": 1},
            "utf8_sha256": {"type": "string", "pattern": SHA256_PATTERN},
            "token_ids": {"type": "array", "minItems": min_tokens,
                          "items": {"type": "integer", "minimum": 0}},
            "token_count": {"type": "integer", "minimum": min_tokens},
        },
    }


def acquisition_schema():
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://study3r.invalid/"
               "study3r_checkpoint_acquisition_v1.schema.json",
        "title": "Study 3R sealed tokenizer-only acquisition record",
        "type": "object",
        "additionalProperties": False,
        "required": ["authority", "checkpoints", "counters",
                     "download_allow_list", "library_versions",
                     "network_request_count", "network_requests",
                     "no_weight_file_proof", "observation_timestamp_utc",
                     "rp_b_ladder", "rp_b_ladder_length", "schema_version",
                     "target_checkpoint", "trust_remote_code"],
        "properties": {
            "schema_version": {"const": "study3r-checkpoint-acquisition-v1"},
            "authority": {"const":
                          "studies/study3r/prompts/"
                          "study3r_protocol_v1_authoring_authority.md"},
            "observation_timestamp_utc": {
                "type": "string",
                "pattern": r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:"
                           r"[0-9]{2}Z$"},
            "target_checkpoint": {"const": TARGET_CHECKPOINT},
            "rp_b_ladder": {"type": "array", "minItems": 3, "maxItems": 3,
                            "prefixItems": [{"const": repo}
                                            for repo in RP_B_LADDER]},
            "rp_b_ladder_length": {"const": 3},
            "download_allow_list": {
                "type": "array", "minItems": 1,
                "items": {"type": "string", "enum": list(DOWNLOAD_ALLOW_LIST)}},
            "trust_remote_code": {"const": False},
            "checkpoints": {
                "type": "array", "minItems": 4, "maxItems": 4,
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["acquired_files", "immutable_revision",
                                 "local_paths_on_disk",
                                 "repository_id",
                                 "repository_paths_at_revision", "role",
                                 "weight_bytes_acquired",
                                 "weight_paths_present_in_repository",
                                 "weight_paths_requested"],
                    "properties": {
                        "role": {"type": "string", "enum": _ROLE_IDS},
                        "repository_id": {"type": "string",
                                          "enum": _REPOSITORY_IDS},
                        "immutable_revision": {"type": "string",
                                               "pattern": REVISION_PATTERN},
                        "acquired_files": {
                            "type": "array", "minItems": 3,
                            "items": {
                                "type": "object",
                                "additionalProperties": False,
                                "required": ["bytes", "path", "sha256"],
                                "properties": {
                                    "path": {"type": "string",
                                             "enum": list(DOWNLOAD_ALLOW_LIST)},
                                    "bytes": {"type": "integer", "minimum": 1},
                                    "sha256": {"type": "string",
                                               "pattern": SHA256_PATTERN},
                                },
                            },
                        },
                        "repository_paths_at_revision": {
                            "type": "array", "minItems": 1,
                            "items": {"type": "string", "minLength": 1}},
                        "weight_paths_present_in_repository": {
                            "type": "array", "minItems": 1,
                            "items": {"type": "string", "minLength": 1}},
                        "weight_paths_requested": {
                            "type": "array", "maxItems": 0,
                            "items": {"type": "string"}},
                        "weight_bytes_acquired": {"const": 0},
                        "local_paths_on_disk": {
                            "type": "array", "minItems": 3,
                            "items": {"type": "string", "minLength": 1}},
                    },
                },
            },
            "no_weight_file_proof": {
                "type": "object",
                "additionalProperties": False,
                "required": ["every_acquired_path_is_in_the_allow_list",
                             "no_acquired_path_has_a_weight_suffix",
                             "weight_bytes_acquired_total",
                             "weight_files_acquired_total",
                             "weight_paths_requested_total",
                             "weight_suffixes_treated_as_weight_bearing"],
                "properties": {
                    "weight_suffixes_treated_as_weight_bearing": {
                        "type": "array", "minItems": 1,
                        "items": {"type": "string",
                                  "enum": list(WEIGHT_SUFFIXES)}},
                    "weight_paths_requested_total": {"const": 0},
                    "weight_files_acquired_total": {"const": 0},
                    "weight_bytes_acquired_total": {"const": 0},
                    "every_acquired_path_is_in_the_allow_list": {"const": True},
                    "no_acquired_path_has_a_weight_suffix": {"const": True},
                },
            },
            "library_versions": {
                "type": "object",
                "additionalProperties": False,
                "required": ["huggingface_hub", "python", "tokenizers",
                             "transformers"],
                "properties": {
                    "python": {"type": "string", "minLength": 1},
                    "transformers": {"type": "string", "minLength": 1},
                    "tokenizers": {"type": "string", "minLength": 1},
                    "huggingface_hub": {"type": "string", "minLength": 1},
                },
            },
            "network_requests": {
                "type": "array", "minItems": 1,
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["kind", "method", "url"],
                    "properties": {
                        "kind": {"type": "string",
                                 "enum": ["metadata", "file"]},
                        "method": {"const": "GET"},
                        "url": {"type": "string",
                                "pattern": r"^https://huggingface\.co/"},
                    },
                },
            },
            "network_request_count": {"type": "integer", "minimum": 1},
            "counters": {
                "type": "object",
                "additionalProperties": False,
                "required": sorted(COUNTERS),
                "properties": {
                    name: ({"const": 0}
                           if name in _ZERO_COUNTER_NAMES
                           else {"type": "integer", "minimum": 1})
                    for name in COUNTERS
                },
            },
        },
    }


_ZERO_COUNTER_NAMES = (
    "decode_calls",
    "weight_files_acquired", "model_constructions", "forward_passes",
    "prefill_operations", "logit_reads", "scoring_operations", "generations",
    "gpu_or_cloud_jobs", "remote_code_executions", "scientific_items_realized",
    "execution_seeds_drawn", "interfaces_selected",
    "evidence_ledger_rows_written",
)


def surfaces_schema():
    label_surfaces = {
        "type": "object",
        "additionalProperties": False,
        "required": list(tasks.LABELS),
        "properties": {label: _surface_schema() for label in tasks.LABELS},
    }
    arm_schema = {
        "type": "object",
        "additionalProperties": False,
        "required": ["arm_id", "d0_candidates",
                     "d0_common_prefix_token_ids",
                     "d0_common_prefix_token_length",
                     "d0_discriminant_position", "d0_discriminant_token_ids",
                     "prompt"],
        "properties": {
            "arm_id": {"type": "string", "enum": [RAW_ARM_ID, CHAT_ARM_ID]},
            "prompt": _surface_schema(),
            "d0_candidates": {
                "type": "object",
                "additionalProperties": False,
                "required": list(tasks.LABELS),
                "properties": {
                    label: {
                        "type": "object",
                        "additionalProperties": False,
                        "required": ["candidate_text", "candidate_token_count",
                                     "candidate_token_ids"],
                        "properties": {
                            "candidate_text": {"type": "string",
                                               "minLength": 1},
                            "candidate_token_ids": {
                                "type": "array", "minItems": 2,
                                "items": {"type": "integer", "minimum": 0}},
                            "candidate_token_count": {"type": "integer",
                                                      "minimum": 2},
                        },
                    } for label in tasks.LABELS
                },
            },
            "d0_common_prefix_token_length": {"type": "integer", "minimum": 1},
            "d0_common_prefix_token_ids": {
                "type": "array", "minItems": 1,
                "items": {"type": "integer", "minimum": 0}},
            "d0_discriminant_position": {"type": "integer", "minimum": 1},
            "d0_discriminant_token_ids": {
                "type": "object",
                "additionalProperties": False,
                "required": list(tasks.LABELS),
                "properties": {label: {"type": "integer", "minimum": 0}
                               for label in tasks.LABELS},
            },
        },
    }
    item_schema = {
        "type": "object",
        "additionalProperties": False,
        "required": ["correct_index", "correct_label", "depth", "family",
                     "is_scientific_item", "item_body", "item_key",
                     "operands", "operations", "options", "stem", "value"],
        "properties": {
            "family": {"type": "string",
                       "enum": sorted(tasks.FAMILY_DEPTH)},
            "depth": {"type": "integer", "minimum": 0, "maximum": 3},
            "operands": {"type": "array", "maxItems": 4,
                         "items": {"type": "integer", "minimum": 0}},
            "operations": {"type": "array", "maxItems": 3,
                           "items": {"type": "string",
                                     "enum": sorted(tasks.OPERATIONS)}},
            "value": {"type": "integer", "minimum": 0},
            "options": {"type": "array", "minItems": 4, "maxItems": 4,
                        "items": {"type": "integer", "minimum": 0}},
            "correct_index": {"type": "integer", "minimum": 0, "maximum": 3},
            "correct_label": {"type": "string", "enum": list(tasks.LABELS)},
            "stem": {"type": "string", "minLength": 1},
            "item_body": {"type": "string", "minLength": 1},
            "item_key": {"type": "string", "pattern": SHA256_PATTERN},
            "is_scientific_item": {"const": False},
        },
    }
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://study3r.invalid/"
               "study3r_tokenizer_surfaces_v1.schema.json",
        "title": "Study 3R frozen byte and token surfaces",
        "type": "object",
        "additionalProperties": False,
        "required": ["answer_cue", "arm_differentiating_field", "arm_ids",
                     "authority", "canonical_fixture", "checkpoints",
                     "cot_route_id", "item_body_template", "label_alphabet",
                     "raw_envelope_separator", "schema_version",
                     "tokenizer_fixtures"],
        "properties": {
            "schema_version": {"const": "study3r-tokenizer-surfaces-v1"},
            "authority": {"const":
                          "studies/study3r/prompts/"
                          "study3r_protocol_v1_authoring_authority.md"},
            "arm_ids": {"type": "array", "minItems": 2, "maxItems": 2,
                        "prefixItems": [{"const": RAW_ARM_ID},
                                        {"const": CHAT_ARM_ID}]},
            "arm_differentiating_field": {"const": ARM_DIFFERENTIATING_FIELD},
            "cot_route_id": {"const": COT_ROUTE_ID},
            "label_alphabet": {"type": "array", "minItems": 4, "maxItems": 4,
                               "prefixItems": [{"const": label}
                                               for label in tasks.LABELS]},
            "item_body_template": {"type": "string", "minLength": 1},
            "answer_cue": {"const": tasks.ANSWER_CUE},
            "raw_envelope_separator": {"const": tasks.RAW_ENVELOPE_SEPARATOR},
            "canonical_fixture": item_schema,
            "tokenizer_fixtures": {"type": "array", "minItems": 6,
                                   "items": item_schema},
            "checkpoints": {
                "type": "array", "minItems": 4, "maxItems": 4,
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["acquired_file_hashes", "arms",
                                 "chat_template_bytes", "chat_template_sha256",
                                 "cot_route", "e0", "immutable_revision",
                                 "max_position_embeddings", "model_type",
                                 "repository_id", "role",
                                 "role_canonical_envelope", "special_tokens",
                                 "tokenizer_class", "tokenizer_vocab_size",
                                 "trust_remote_code", "vocab_size_from_config"],
                    "properties": {
                        "role": {"type": "string", "enum": _ROLE_IDS},
                        "repository_id": {"type": "string",
                                          "enum": _REPOSITORY_IDS},
                        "immutable_revision": {"type": "string",
                                               "pattern": REVISION_PATTERN},
                        "tokenizer_class": {"type": "string", "minLength": 1},
                        "vocab_size_from_config": {"type": "integer",
                                                   "minimum": 1},
                        "tokenizer_vocab_size": {"type": "integer",
                                                 "minimum": 1},
                        "max_position_embeddings": {"type": "integer",
                                                    "minimum": 1},
                        "model_type": {"type": "string", "minLength": 1},
                        "trust_remote_code": {"const": False},
                        "special_tokens": {
                            "type": "object",
                            "additionalProperties": False,
                            "required": [
                                "bos_token", "bos_token_id", "eos_token",
                                "eos_token_id",
                                "generation_config_bos_token_id",
                                "generation_config_eos_token_id", "pad_token",
                                "pad_token_id", "tokenizer_config_eos_token",
                                "unk_token"],
                            "properties": {
                                "bos_token": {"type": "string",
                                              "minLength": 1},
                                "bos_token_id": {"type": "integer",
                                                 "minimum": 0},
                                "eos_token": {"type": "string",
                                              "minLength": 1},
                                "eos_token_id": {"type": "integer",
                                                 "minimum": 0},
                                "pad_token": {"type": ["string", "null"],
                                              "minLength": 1},
                                "pad_token_id": {"type": ["integer", "null"],
                                                 "minimum": 0},
                                "unk_token": {"type": ["string", "null"],
                                              "minLength": 1},
                                "tokenizer_config_eos_token": {
                                    "type": "string", "minLength": 1},
                                "generation_config_eos_token_id": {
                                    "type": ["integer", "array"],
                                    "minimum": 0,
                                    "items": {"type": "integer",
                                              "minimum": 0}},
                                "generation_config_bos_token_id": {
                                    "type": ["integer", "null"],
                                    "minimum": 0},
                            },
                        },
                        "chat_template_sha256": {"type": "string",
                                                 "pattern": SHA256_PATTERN},
                        "chat_template_bytes": {"type": "integer",
                                                "minimum": 1},
                        "e0": {
                            "type": "object",
                            "additionalProperties": False,
                            "required": ["add_special_tokens", "do_sample",
                                         "legal_answer_surfaces",
                                         "longest_legal_answer_surface_tokens",
                                         "max_new_tokens",
                                         "termination_margin_tokens"],
                            "properties": {
                                "legal_answer_surfaces": label_surfaces,
                                "longest_legal_answer_surface_tokens": {
                                    "type": "integer", "minimum": 1},
                                "termination_margin_tokens": {
                                    "const": E0_TERMINATION_MARGIN_TOKENS},
                                "max_new_tokens": {"type": "integer",
                                                   "minimum": 2},
                                "add_special_tokens": {"const": False},
                                "do_sample": {"const": False},
                            },
                        },
                        "arms": {
                            "type": "object",
                            "additionalProperties": False,
                            "required": [RAW_ARM_ID, CHAT_ARM_ID],
                            "properties": {RAW_ARM_ID: arm_schema,
                                           CHAT_ARM_ID: arm_schema},
                        },
                        "role_canonical_envelope": {
                            "type": "object",
                            "additionalProperties": False,
                            "required": ["answer_cue",
                                         "frozen_reasoning_closure",
                                         "generation_prompt",
                                         "reasoning_open_marker",
                                         "reasoning_span_opened_by_template"],
                            "properties": {
                                "generation_prompt": _surface_schema(),
                                "reasoning_span_opened_by_template": {
                                    "type": "boolean"},
                                "reasoning_open_marker": {
                                    "type": ["string", "null"],
                                    "enum": list(REASONING_OPEN_MARKERS)
                                            + [None]},
                                "frozen_reasoning_closure": {
                                    "type": "string",
                                    "enum": ["", REASONING_CLOSE_BYTES]},
                                "answer_cue": {"const": tasks.ANSWER_CUE},
                            },
                        },
                        "cot_route": {
                            "type": "object",
                            "additionalProperties": False,
                            "required": ["do_sample", "instruction", "k",
                                         "parser_id", "parser_regex", "prompt",
                                         "route_id"],
                            "properties": {
                                "route_id": {"const": COT_ROUTE_ID},
                                "instruction": {"const": COT_INSTRUCTION},
                                "prompt": _surface_schema(),
                                "parser_id": {"const": COT_PARSER_ID},
                                "parser_regex": {"const": COT_PARSER_REGEX},
                                "k": {"const": 1},
                                "do_sample": {"const": False},
                            },
                        },
                        "acquired_file_hashes": {
                            "type": "object",
                            "minProperties": 3,
                            "additionalProperties": {
                                "type": "string", "pattern": SHA256_PATTERN}},
                    },
                },
            },
        },
    }


def equivalence_schema():
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://study3r.invalid/"
               "study3r_tokenizer_equivalence_v1.schema.json",
        "title": "Study 3R tokenizer functional-equivalence record",
        "type": "object",
        "additionalProperties": False,
        "required": ["authority", "comparisons", "distinct_stratum_count",
                     "pooling_rule", "reference_role", "role_to_stratum",
                     "schema_version", "strata", "verified_tuple_elements"],
        "properties": {
            "schema_version": {"const": "study3r-tokenizer-equivalence-v1"},
            "authority": {"const":
                          "studies/study3r/prompts/"
                          "study3r_protocol_v1_authoring_authority.md"},
            "reference_role": {"const": "RT"},
            "verified_tuple_elements": {
                "type": "array", "minItems": 5, "maxItems": 5,
                "prefixItems": [{"const": "bytes"},
                                {"const": "token_ids"},
                                {"const": "common_prefix"},
                                {"const": "discriminant_position"},
                                {"const": "answer_surface_token_ids"}]},
            "comparisons": {
                "type": "array", "minItems": 8,
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["arm_id", "differing_tuple_elements",
                                 "identical_to_reference", "immutable_revision",
                                 "reference_role", "repository_id", "role"],
                    "properties": {
                        "arm_id": {"type": "string",
                                   "enum": [RAW_ARM_ID, CHAT_ARM_ID]},
                        "reference_role": {"const": "RT"},
                        "role": {"type": "string", "enum": _ROLE_IDS},
                        "repository_id": {"type": "string",
                                          "enum": _REPOSITORY_IDS},
                        "immutable_revision": {"type": "string",
                                               "pattern": REVISION_PATTERN},
                        "identical_to_reference": {"type": "boolean"},
                        "differing_tuple_elements": {
                            "type": "array",
                            "items": {"type": "string",
                                      "enum": ["bytes", "token_ids",
                                               "common_prefix",
                                               "discriminant_position",
                                               "answer_surface_token_ids"]}},
                    },
                },
            },
            "strata": {
                "type": "array", "minItems": 1,
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["roles", "signature_sha256", "stratum_id"],
                    "properties": {
                        "stratum_id": {"type": "string",
                                       "pattern": r"^STRATUM_[0-9]{2}$"},
                        "signature_sha256": {"type": "string",
                                             "pattern": SHA256_PATTERN},
                        "roles": {"type": "array", "minItems": 1,
                                  "items": {"type": "string",
                                            "enum": _ROLE_IDS}},
                    },
                },
            },
            "role_to_stratum": {
                "type": "object",
                "additionalProperties": False,
                "required": _ROLE_IDS,
                "properties": {role: {"type": "string",
                                      "pattern": r"^STRATUM_[0-9]{2}$"}
                               for role in _ROLE_IDS},
            },
            "pooling_rule": {"type": "string", "minLength": 40},
            "distinct_stratum_count": {"type": "integer", "minimum": 1,
                                       "maximum": 4},
        },
    }


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cache-root", required=False,
                        help="directory outside the repository for acquired files")
    parser.add_argument("--out-dir", default=str(ACQUISITION_DIR))
    parser.add_argument("--observation-timestamp", required=False,
                        help="RFC 3339 UTC observation timestamp")
    parser.add_argument("--schemas-only", action="store_true",
                        help="regenerate only the three acquisition schemas; "
                             "performs no network or tokenizer operation")
    args = parser.parse_args(argv)

    out_dir = pathlib.Path(args.out_dir)
    if args.schemas_only:
        write_json(out_dir / "study3r_checkpoint_acquisition_v1.schema.json",
                   acquisition_schema())
        write_json(out_dir / "study3r_tokenizer_surfaces_v1.schema.json",
                   surfaces_schema())
        write_json(out_dir / "study3r_tokenizer_equivalence_v1.schema.json",
                   equivalence_schema())
        print("regenerated 3 acquisition schemas; 0 network requests, "
              "0 tokenizer constructions")
        return 0
    if not args.observation_timestamp:
        parser.error("--observation-timestamp is required for acquisition")

    import huggingface_hub
    import tokenizers
    import transformers

    cache_root = pathlib.Path(args.cache_root)

    records = []
    probes = []
    for role, repo_id in CHECKPOINT_ROLES:
        record = resolve_and_download(repo_id, cache_root)
        record["role"] = role
        records.append(record)
        probes.append(probe_checkpoint(role, record, cache_root))

    acquisition = {
        "schema_version": "study3r-checkpoint-acquisition-v1",
        "authority":
            "studies/study3r/prompts/study3r_protocol_v1_authoring_authority.md",
        "observation_timestamp_utc": args.observation_timestamp,
        "target_checkpoint": TARGET_CHECKPOINT,
        "rp_b_ladder": list(RP_B_LADDER),
        "rp_b_ladder_length": len(RP_B_LADDER),
        "download_allow_list": list(DOWNLOAD_ALLOW_LIST),
        "trust_remote_code": False,
        "checkpoints": [
            {
                "role": record["role"],
                "repository_id": record["repository_id"],
                "immutable_revision": record["immutable_revision"],
                "acquired_files": record["acquired_files"],
                "repository_paths_at_revision":
                    record["repository_paths_at_revision"],
                "weight_paths_present_in_repository":
                    record["weight_paths_present_in_repository"],
                "weight_paths_requested": record["weight_paths_requested"],
                "weight_bytes_acquired": record["weight_bytes_acquired"],
                "local_paths_on_disk": record["local_paths_on_disk"],
            }
            for record in records
        ],
        "no_weight_file_proof": {
            "weight_suffixes_treated_as_weight_bearing": list(WEIGHT_SUFFIXES),
            "weight_paths_requested_total": 0,
            "weight_files_acquired_total": COUNTERS["weight_files_acquired"],
            "weight_bytes_acquired_total": 0,
            "every_acquired_path_is_in_the_allow_list": all(
                entry["path"] in DOWNLOAD_ALLOW_LIST
                for record in records for entry in record["acquired_files"]),
            "no_acquired_path_has_a_weight_suffix": all(
                not entry["path"].lower().endswith(WEIGHT_SUFFIXES)
                for record in records for entry in record["acquired_files"]),
        },
        "library_versions": {
            "python": platform.python_version(),
            "transformers": transformers.__version__,
            "tokenizers": tokenizers.__version__,
            "huggingface_hub": huggingface_hub.__version__,
        },
        "network_requests": NETWORK_LOG,
        "network_request_count": len(NETWORK_LOG),
        "counters": dict(COUNTERS),
    }

    surfaces = {
        "schema_version": "study3r-tokenizer-surfaces-v1",
        "authority":
            "studies/study3r/prompts/study3r_protocol_v1_authoring_authority.md",
        "arm_ids": [RAW_ARM_ID, CHAT_ARM_ID],
        "arm_differentiating_field": ARM_DIFFERENTIATING_FIELD,
        "cot_route_id": COT_ROUTE_ID,
        "label_alphabet": list(tasks.LABELS),
        "item_body_template": tasks.ITEM_BODY_TEMPLATE,
        "answer_cue": tasks.ANSWER_CUE,
        "raw_envelope_separator": tasks.RAW_ENVELOPE_SEPARATOR,
        "canonical_fixture": tasks.canonical_fixture(),
        "tokenizer_fixtures": tasks.tokenizer_fixtures(),
        "checkpoints": probes,
    }

    equivalence = {
        "schema_version": "study3r-tokenizer-equivalence-v1",
        "authority":
            "studies/study3r/prompts/study3r_protocol_v1_authoring_authority.md",
    }
    equivalence.update(build_equivalence(probes))

    write_json(out_dir / "study3r_checkpoint_acquisition_v1.json", acquisition)
    write_json(out_dir / "study3r_checkpoint_acquisition_v1.schema.json",
               acquisition_schema())
    write_json(out_dir / "study3r_tokenizer_surfaces_v1.json", surfaces)
    write_json(out_dir / "study3r_tokenizer_surfaces_v1.schema.json",
               surfaces_schema())
    write_json(out_dir / "study3r_tokenizer_equivalence_v1.json", equivalence)
    write_json(out_dir / "study3r_tokenizer_equivalence_v1.schema.json",
               equivalence_schema())
    print("acquired %d checkpoints; strata=%d; counters=%s"
          % (len(probes), equivalence["distinct_stratum_count"],
             json.dumps(COUNTERS, sort_keys=True)))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
