"""Render the committed OD-017 audit as a readable table.

Authority section 10 requires every conformance entry to be reported. The JSON
is the artifact of record; this renders it so a reader does not have to parse
it, and it renders FROM that file rather than from a retyped copy, so the two
cannot drift.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def escape(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--audit", required=True)
    parser.add_argument("--non-vacuity", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    audit = json.loads(Path(args.audit).read_text(encoding="utf-8"))
    vacuity = json.loads(Path(args.non_vacuity).read_text(encoding="utf-8"))

    lines = [
        "# P-0 gate results, rendered from the committed artifacts",
        "",
        "Generated by `tools/render_gates.py` from `out/od017_conformance.json`",
        "and `out/non_vacuity_demonstration.json`. Nothing here is retyped, so",
        "this document cannot drift from the artifacts of record.",
        "",
        "---",
        "",
        "## OD-011 — non-vacuity demonstration",
        "",
        f"Null source: **{vacuity['null_source']}**, seed `{vacuity['seed']}`, "
        f"{vacuity['clusters']} clusters, "
        f"sigma {vacuity['null_sigmas']}.",
        "",
        f"Proven before any real curve was judged: "
        f"**{vacuity['proven_before_any_real_curve_was_judged']}**.",
        "",
        "| case | must return | returned | layers above ceiling | result |",
        "|---|---|---|---|---|",
    ]
    for name, case in vacuity["cases"].items():
        lines.append(
            f"| `{name}` | `{case['must_be']}` | `{case['verdict']}` | "
            f"{case['layers_above_ceiling']} | "
            f"{'PASS' if case['passed'] else 'FAIL'} |"
        )
    lines += [
        "",
        f"All passed: **{vacuity['all_passed']}**.",
        "",
        f"> {vacuity['meaning']}",
        "",
        "---",
        "",
        "## OD-017 — registered text against live implementation",
        "",
        f"**{audit['n_entries']} entries, {audit['n_divergences']} divergences, "
        f"verdict `{audit['verdict']}`.**",
        "",
        f"Method: {audit['method']}",
        "",
        f"Directionality precedent: {audit['directionality_precedent']}",
        "",
        "| # | registered id | verdict | registered value | observed value |",
        "|---|---|---|---|---|",
    ]
    for index, entry in enumerate(audit["entries"], start=1):
        lines.append(
            f"| {index} | `{escape(entry['registered_id'])}` | "
            f"**{entry['verdict']}** | "
            f"`{escape(json.dumps(entry['registered_value'], ensure_ascii=False))[:70]}` | "
            f"`{escape(json.dumps(entry['observed_value'], ensure_ascii=False))[:70]}` |"
        )

    lines += ["", "### What each entry checks", ""]
    for index, entry in enumerate(audit["entries"], start=1):
        lines += [
            f"**{index}. `{entry['registered_id']}`** — {entry['verdict']}",
            "",
            f"- registered: {escape(entry['registered_text'])}",
            f"- implemented by: `{escape(entry['implementation'])}`",
            f"- what the code does: {escape(entry['what_the_code_actually_does'])}",
        ]
        if entry.get("note"):
            lines.append(f"- note: {escape(entry['note'])}")
        lines.append("")

    Path(args.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"rendered {audit['n_entries']} OD-017 entries and "
        f"{len(vacuity['cases'])} OD-011 cases"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
