"""Render P-0' gate results from the committed artifacts.

The directive asks for every conformance entry and every case result. A JSON
blob is technically compliance and practically not, so this renders a readable
table FROM the artifacts of record rather than from a retyped copy, which means
the readable version cannot drift from them.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def esc(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--audit", required=True)
    parser.add_argument("--non-vacuity", required=True)
    parser.add_argument("--baseline", required=True)
    parser.add_argument("--inclusion", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    audit = json.loads(Path(args.audit).read_text(encoding="utf-8"))
    vac = json.loads(Path(args.non_vacuity).read_text(encoding="utf-8"))
    base = json.loads(Path(args.baseline).read_text(encoding="utf-8"))
    inc = json.loads(Path(args.inclusion).read_text(encoding="utf-8"))

    out: list[str] = []
    add = out.append

    add("# P-0' gate results, rendered from the committed artifacts")
    add("")
    add(
        "Generated by `tools/render_gates_p0prime.py` from the JSON artifacts "
        "of record. Nothing here is retyped, so this document cannot drift "
        "from them."
    )
    add("")
    add(
        "In the case table, *worst |mean|* is the pooled mean itself, so a case "
        "required to return 1 shows 1 and a case required to be positive shows "
        "its magnitude. *Interval contains 0* is required only of the two "
        "must-be-zero cases."
    )
    add("")
    add("---")
    add("")
    add("## OD-011 as revised — the four synthetic cases")
    add("")
    add(
        "Estimand under test: **the one the directive prescribed**, "
        f"`{vac['estimand_formula']}`."
    )
    add("")
    add(f"How *approximately zero* is formalised: {vac['how_approximately_zero_is_formalised']}")
    add("")
    add("| case | must return | worst \\|mean\\| | interval contains 0 | result |")
    add("|---|---|---|---|---|")
    for name, case in sorted(vac["cases"].items()):
        mark = "PASS" if case["passed"] else "**FAIL**"
        add(
            f"| `{name}` | `{case['must_be']}` | {case['worst_abs_mean']:.6f} | "
            f"{case['every_layer_interval_contains_zero']} | {mark} |"
        )
    add("")
    add(f"All passed: **{vac['all_passed']}**.")
    add("")
    note = vac["analytic"]
    sweep = note["sweep_over_plausible_clean_runs"]
    add("### Why case 2 fails, in closed form")
    add("")
    add(f"> {note['substitution']}")
    add(">")
    add(f"> `{note['closed_form']}`")
    add(">")
    add(f"> {note['consequence']}")
    add("")
    add(
        f"Swept over {sweep['draws']} plausible clean-run pairs, using no P-0 "
        f"data: min {sweep['min']:.4f}, mean {sweep['mean']:.4f}, max "
        f"{sweep['max']:.4f}, **fraction at or below zero "
        f"{sweep['fraction_at_or_below_zero']:.4f}**."
    )
    add("")
    add("---")
    add("")
    add("## No-op integrity after the three-part batch repair")
    add("")
    add(
        f"dtype `{base['dtype']}`, {base['n_units']} units, batch "
        f"{base['batch']}, tolerance {base['tolerance_normalised']:.0e} normalised."
    )
    add("")
    add("| family | worst \\|mean\\| normalised | worst single unit | worst \\|mean\\| logits |")
    add("|---|---|---|---|")
    for name, stats in sorted(base["constructions"].items()):
        add(
            f"| `{name}` | {stats['worst_abs_mean_normalised']:.3e} | "
            f"{stats['worst_abs_single_unit_normalised']:.3e} | "
            f"{stats['worst_abs_mean_logits']:.3e} |"
        )
    add("")
    add(f"**Verdict {base['verdict']}** — bit-exact, not merely within tolerance.")
    add("")
    add(
        "Baseline shift against a batch-of-one forward: "
        f"{base['old_batch_of_one_baseline_shift_logits']['mean']:.6f} logits."
    )
    add("")
    add("---")
    add("")
    add("## Registered inclusion")
    add("")
    add("| | |")
    add("|---|---|")
    add(f"| units measured in P-0 | {inc['population']['units_measured_in_P0']} |")
    add(
        f"| correct on both sides | **{inc['correct_both']['units']} units, "
        f"{inc['correct_both']['clusters']} clusters** |"
    )
    add(
        f"| after the denominator floor | "
        f"{inc['after_the_denominator_floor']['units']} units |"
    )
    add(f"| registered floor | {inc['n_floor']} |")
    add(f"| meets the floor | **{inc['meets_the_floor']}** |")
    add("")
    add("---")
    add("")
    add("## OD-017 conformance")
    add("")
    add(
        f"**{audit['n_entries']} entries, {audit['n_divergences']} divergence(s), "
        f"verdict `{audit['verdict']}`.**"
    )
    add("")
    add(f"> {audit['note_on_the_expected_divergence']}")
    add("")
    add("| # | registered id | verdict | registered | observed |")
    add("|---|---|---|---|---|")
    for index, entry in enumerate(audit["entries"], start=1):
        reg = esc(json.dumps(entry["registered_value"], ensure_ascii=False))[:58]
        obs = esc(json.dumps(entry["observed_value"], ensure_ascii=False))[:58]
        add(
            f"| {index} | `{esc(entry['registered_id'])}` | "
            f"**{entry['verdict']}** | `{reg}` | `{obs}` |"
        )
    add("")
    add("### What each entry checks")
    add("")
    for index, entry in enumerate(audit["entries"], start=1):
        add(f"**{index}. `{entry['registered_id']}`** — {entry['verdict']}")
        add("")
        add(f"- registered: {esc(entry['registered_text'])}")
        add(f"- implemented by: `{esc(entry['implementation'])}`")
        add(f"- what the code does: {esc(entry['what_the_code_actually_does'])}")
        if entry.get("note"):
            add(f"- note: {esc(entry['note'])}")
        if entry.get("why_this_entry_exists"):
            add(f"- why this entry exists: {esc(entry['why_this_entry_exists'])}")
        add("")

    Path(args.out).write_text("\n".join(out) + "\n", encoding="utf-8")
    print(
        f"rendered {audit['n_entries']} OD-017 entries and "
        f"{len(vac['cases'])} synthetic cases"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
