#!/usr/bin/env python3
"""Study 3 P0-R2 generation-2 execution lock.

Authority:
``studies/study3/prompts/study3_p0_r2_generation2_successor_and_conditional_execution_authority.md``
sections 5, 6.1 and 8.

The lock is the single document every later generation-2 proof is bound to. It
binds, from committed Git objects only:

* this authority's exact committed bytes;
* the generation-2 executable commit and tree, and every image-bound path;
* the new image digest, its base digest and the exact ACR task blob;
* the reused scientific bytes, together with the registered generation-1
  identities they must equal, so immutability is *proved* rather than asserted;
* the generation-2 namespace, attempt identities, blob prefixes and job names;
* the bounded-pilot maxima, the permanent governance state and the prohibitions.

The schema is generated by this module and validated by the v2 schema walker,
which is imported rather than restated so the two generations cannot drift.

Model-free: this module reads Git objects and hashes bytes.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys


P0_R2_DIR = Path(__file__).resolve().parent
if str(P0_R2_DIR) not in sys.path:
    sys.path.insert(0, str(P0_R2_DIR))

import p0_r2_execution_lock_v2 as V2  # noqa: E402
import p0_r2_namespace_g2 as NS  # noqa: E402
import p0_r2_prefix_proof_g2 as PREFIX  # noqa: E402


REPO_ROOT = P0_R2_DIR.parent.parent.parent.parent

SCHEMA_VERSION = "study3-p0-r2-execution-lock-g2"
STAGE = "STUDY3-P0-R2"
GENERATION = 2
LOCK_NAME = "p0_r2_execution_lock_g2.json"
SCHEMA_NAME = "p0_r2_execution_lock_g2.schema.json"
TERMINAL_STATE = "STUDY3_P0_R2_GENERATION2_EXECUTION_READY_AWAITING_REPLAY_GATE"

AUTHORITY_PATH = (
    "studies/study3/prompts/"
    "study3_p0_r2_generation2_successor_and_conditional_execution_authority.md")
TASK_PATH = "studies/study3/pilot/p0_r2/container/p0_r2_acr_task_g2.yaml"

#: Section 15. Enforced by the runner, never merely reported.
CAPS = {
    "max_smoke_prefills_before_extension": 60,
    "max_non_generative_prefills": 180,
    "max_s4_generations": 12,
    "max_model_evaluation_equivalents": 228,
    "possible_scored_rows": 210,
}

PRE_REPLAY_COUNTERS = {
    "tokenizer_constructions": 0, "tokenizer_encodes": 0,
    "checkpoint_downloads": 0, "checkpoint_loads": 0,
    "model_weight_loads": 0, "prefills": 0, "generations": 0,
    "scored_rows": 0, "evidence_rows_added": 0,
    "gpu_allocations": 0, "gpu_operations": 0,
    "live_replay_invocations": 0, "pilot_executions_started": 0,
}

STANDING_FAILURES = tuple(V2.STANDING_FAILURES)

LEGAL_STATE = {
    "formal_execution_authorized": False,
    "draft_v0_6_reviewed": False,
    "draft_v0_6_frozen": False,
    "interface": None,
    "positive_reference": None,
    "rp_wrapper": None,
    "evidence_ledger_tail": "EV-0016",
    "research_question_answered": False,
}

#: Section 2. These stay exactly as generation 1 published them.
GENERATION1_TERMINAL = {
    "closure_head": "135f725baff7f5c9c1b0ae15ad5692bf77dd4fc5",
    "ready_anchor": "7ff6700621ca1db9bdf06d1d91a49e935e66e2b7",
    "image_executable": "c9344c52bfbacc4f2a24010fffa534a940104140",
    "image_digest":
        "sha256:eb0e284c6b420aa4992dcdee9a43b9cb92a96937499bca605f96b141619e9b58",
    "consumed_attempt": "p0r2-g1-live-20260815-0800",
    "acr_run_id": "cmjv",
    "live_invocations": 1,
    "acr_run_ids": 1,
    "replay_gate_invocations": 0,
    "recovered_canonical_artifacts": 0,
    "state": "STOP_NO_MODEL_OPERATION",
}

P0_R1_TERMINAL = {
    "stop_commit": "30806d793872a50e581d3252382b4a0ec2af3889",
    "state": "STOP_NO_MODEL_OPERATION",
    "replay_envelope_consumed": True,
    "launchable": False,
}

FROZEN_ROOTS = (
    "studies/study3/pilot/p0_r1/",
    "studies/study3/pilot/p0/results/p0-r1/",
    "studies/study3/pilot/p0_r2/",
    "studies/study3/pilot/p0/results/p0-r2/",
)

PROHIBITIONS = {
    "rerun_replay": True,
    "regenerate_replay": True,
    "substitute_another_attempt": True,
    "repair_the_gate_in_place": True,
    "second_az_acr_run_live": True,
    "create_success_artifacts_without_recovered_bytes": True,
    "update_or_repurpose_an_existing_gpu_job": True,
    "second_start_to_resolve_ambiguity": True,
    "set_live_replay_authorized_globally": True,
    "edit_generation1_or_p0_r1_bytes": True,
    "caller_supplied_governance_allowlist": True,
    "reuse_a_generation1_attempt_prefix_job_or_receipt": True,
}


class LockDefect(Exception):
    """A generation-2 lock stop."""


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def canonical_bytes(document) -> bytes:
    return json.dumps(document, indent=2, sort_keys=True).encode("utf-8") + b"\n"


def _git(root, args, *, binary=False):
    completed = subprocess.run(  # noqa: S603 - fixed executable
        ["git", "-C", str(root), *args], capture_output=True,
        text=not binary, check=False)
    if completed.returncode:
        message = completed.stderr if not binary \
            else completed.stderr.decode("utf-8", "replace")
        raise LockDefect("git %s refused: %s" % (" ".join(args), message.strip()))
    return completed.stdout


def blob_identity(root, commit, repo_path) -> dict:
    listing = _git(root, ["ls-tree", commit, "--", repo_path]).strip()
    if not listing:
        raise LockDefect("%s does not exist at %s" % (repo_path, commit[:12]))
    mode, kind, rest = listing.split(" ", 2)
    blob, _, _ = rest.partition("\t")
    if kind != "blob":
        raise LockDefect("%s is not a regular blob" % repo_path)
    payload = _git(root, ["cat-file", "blob", blob], binary=True)
    return {
        "path": repo_path,
        "mode": mode,
        "git_blob": blob,
        "bytes": len(payload),
        "sha256": _sha256(payload),
    }


def build(root=None, *, inputs) -> dict:
    """Assemble the generation-2 lock from committed objects and receipts."""
    root = Path(root or REPO_ROOT).resolve()
    required = ("executable_commit", "image_digest", "base_digest",
                "image_reference", "image_tag", "build_run_id",
                "live_attempt_id", "pilot_attempt_id")
    missing = [name for name in required if not inputs.get(name)]
    if missing:
        raise LockDefect("the lock requires %s" % ", ".join(sorted(missing)))

    executable_commit = _git(
        root, ["rev-parse", inputs["executable_commit"] + "^{commit}"]).strip()
    executable_tree = _git(
        root, ["rev-parse", inputs["executable_commit"] + "^{tree}"]).strip()

    authority = blob_identity(root, executable_commit, AUTHORITY_PATH)
    task = blob_identity(root, executable_commit, TASK_PATH)

    import p0_r2_image_manifest_g2 as MANIFEST  # noqa: E402

    manifest = MANIFEST.build(root, commit=executable_commit)

    scientific = []
    for entry in manifest["entries"]:
        if entry["kind"] != "scientific":
            continue
        scientific.append({
            "path": entry["path"],
            "bytes": entry["bytes"],
            "sha256": entry["sha256"],
            "git_blob": entry["git_blob"],
        })
    registered = inputs.get("registered_science") or {}
    immutable_science_proved = True
    science_comparison = []
    for entry in scientific:
        expected = registered.get(entry["path"])
        agrees = expected is None or (
            expected.get("sha256") == entry["sha256"]
            and expected.get("bytes") == entry["bytes"])
        if not agrees:
            immutable_science_proved = False
        science_comparison.append({
            "path": entry["path"],
            "generation2_sha256": entry["sha256"],
            "registered_sha256": (expected or {}).get("sha256"),
            "agrees": bool(agrees),
            "compared": expected is not None,
        })

    delegated = [entry for entry in scientific
                 if entry["path"].startswith("studies/study3/pilot/p0_r1/")]

    live_attempt = inputs["live_attempt_id"]
    pilot_attempt = inputs["pilot_attempt_id"]
    for attempt, prefix in ((live_attempt, NS.LIVE_ATTEMPT_PREFIX),
                            (pilot_attempt, NS.PILOT_ATTEMPT_PREFIX)):
        if not attempt.startswith(prefix):
            raise LockDefect("%r does not begin %r" % (attempt, prefix))
    NS.assert_disjoint_from_generation1([live_attempt, pilot_attempt])

    document = {
        "schema_version": SCHEMA_VERSION,
        "stage": STAGE,
        "generation": GENERATION,
        "revision": 1,
        "terminal_state": TERMINAL_STATE,
        "self": {"name": LOCK_NAME, "schema": SCHEMA_NAME},
        "authority": authority,
        "image_executable": {
            "commit": executable_commit,
            "tree": executable_tree,
            "file_count": manifest["entry_count"],
            "entries_sha256": manifest["entries_sha256"],
            "manifest_name": MANIFEST.MANIFEST_NAME,
        },
        "image": {
            "reference": inputs["image_reference"],
            "digest": inputs["image_digest"],
            "base_digest": inputs["base_digest"],
            "tag": inputs["image_tag"],
            "build_run_id": inputs["build_run_id"],
            "is_new_digest": inputs["image_digest"]
            != GENERATION1_TERMINAL["image_digest"],
        },
        "transport": {
            "task_path": TASK_PATH,
            "task_blob": task["git_blob"],
            "task_bytes": task["bytes"],
            "task_sha256": task["sha256"],
            "context_entry_count": 2,
            "context_entries": ["context_manifest.json", "task.yaml"],
            "context_is_executable_code": False,
            "max_native_context_path": 100,
        },
        "namespace": {
            "prefix_root": NS.PREFIX_ROOT,
            "attempt_id_prefix": NS.ATTEMPT_ID_PREFIX,
            "live_replay_attempt_id": live_attempt,
            "pilot_attempt_id": pilot_attempt,
            "live_blob_prefix": NS.attempt_prefix(live_attempt),
            "pilot_blob_prefix": NS.attempt_prefix(pilot_attempt),
            "results_root": NS.RESULTS_ROOT,
            "disjoint_from_generation1": True,
        },
        "azure": {
            "subscription": PREFIX.SUBSCRIPTION,
            "resource_group": PREFIX.RESOURCE_GROUP,
            "registry": "acrjspaceobssea0708231738",
            "storage_account": PREFIX.ACCOUNT,
            "results_container": PREFIX.CONTAINER,
            "container_apps_environment": PREFIX.ACA_ENVIRONMENT,
            "gpu_job": NS.GPU_JOB,
            "recovery_job": NS.RECOVERY_JOB,
            "prefix_job": NS.PREFIX_JOB,
            "hard_kill_job": NS.HARD_KILL_JOB,
        },
        "prefix_proof": {
            "performed_in_vnet": True,
            "performed_in_acr": False,
            "shared_canary_and_live_validator": True,
            "validator": "p0_r2_prefix_proof_g2.validate_receipt",
            "max_host_observation_age_seconds":
                PREFIX.MAX_HOST_OBSERVATION_AGE_SECONDS,
            "receipt_schema_version": PREFIX.SCHEMA_VERSION,
        },
        "immutable_sources": scientific,
        "delegated_scientific_modules": delegated,
        "immutable_science": {
            "proved": immutable_science_proved,
            "comparison": science_comparison,
            "science_is_unchanged_p0_r1_generation3": True,
        },
        "generation1_terminal": dict(GENERATION1_TERMINAL),
        "p0_r1_terminal": dict(P0_R1_TERMINAL),
        "frozen_roots": list(FROZEN_ROOTS),
        "replay_envelope": {
            "consumed": False,
            "invocations": 0,
            "consumed_on_invocation_even_without_a_run_id": True,
            "rerunnable": False,
        },
        "caps": dict(CAPS),
        "caps_are_enforced_not_reported": True,
        "pre_replay_counters": dict(PRE_REPLAY_COUNTERS),
        "standing_failures": list(STANDING_FAILURES),
        "governance_evidence_closure": list(
            inputs.get("governance_evidence_closure") or []),
        "canaries": list(inputs.get("canaries") or []),
        "attempt_ledger": inputs.get("attempt_ledger"),
        "legal_state": dict(LEGAL_STATE),
        "prohibitions": dict(PROHIBITIONS),
    }
    document["self"]["sha256"] = None
    payload = canonical_bytes(document)
    document["self"]["sha256"] = _sha256(payload)
    return document


def schema() -> dict:
    """The generation-2 schema, generated rather than transcribed."""
    string = {"type": "string"}
    sha256 = {"type": "string", "pattern": "^[0-9a-f]{64}$"}
    sha40 = {"type": "string", "pattern": "^[0-9a-f]{40}$"}
    digest = {"type": "string", "pattern": "^sha256:[0-9a-f]{64}$"}
    blob = {
        "type": "object",
        "required": ["path", "bytes", "sha256", "git_blob"],
        "properties": {"path": string, "bytes": {"type": "integer"},
                       "sha256": sha256, "git_blob": sha40},
    }
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": SCHEMA_NAME,
        "type": "object",
        "required": [
            "schema_version", "stage", "generation", "terminal_state", "self",
            "authority", "image_executable", "image", "transport", "namespace",
            "azure", "prefix_proof", "immutable_sources",
            "delegated_scientific_modules", "immutable_science",
            "generation1_terminal", "p0_r1_terminal", "frozen_roots",
            "replay_envelope", "caps", "pre_replay_counters",
            "standing_failures", "legal_state", "prohibitions",
        ],
        "properties": {
            "schema_version": {"const": SCHEMA_VERSION},
            "stage": {"const": STAGE},
            "generation": {"const": GENERATION},
            "terminal_state": {"const": TERMINAL_STATE},
            "authority": blob,
            "image_executable": {
                "type": "object",
                "required": ["commit", "tree", "file_count", "entries_sha256"],
                "properties": {"commit": sha40, "tree": sha40,
                               "file_count": {"type": "integer"},
                               "entries_sha256": sha256},
            },
            "image": {
                "type": "object",
                "required": ["reference", "digest", "base_digest",
                             "is_new_digest"],
                "properties": {"reference": string, "digest": digest,
                               "base_digest": digest,
                               "is_new_digest": {"const": True}},
            },
            "transport": {
                "type": "object",
                "required": ["task_path", "task_blob", "context_entry_count",
                             "context_entries", "max_native_context_path"],
                "properties": {
                    "task_path": {"const": TASK_PATH},
                    "task_blob": sha40,
                    "context_entry_count": {"const": 2},
                    "context_is_executable_code": {"const": False},
                    "max_native_context_path": {"const": 100},
                },
            },
            "namespace": {
                "type": "object",
                "required": ["prefix_root", "attempt_id_prefix",
                             "live_replay_attempt_id", "pilot_attempt_id",
                             "live_blob_prefix", "pilot_blob_prefix"],
                "properties": {
                    "prefix_root": {"const": NS.PREFIX_ROOT},
                    "attempt_id_prefix": {"const": NS.ATTEMPT_ID_PREFIX},
                    "live_replay_attempt_id": {
                        "type": "string",
                        "pattern": "^p0r2-g2-live-"},
                    "pilot_attempt_id": {
                        "type": "string",
                        "pattern": "^p0r2-g2-pilot-"},
                    "disjoint_from_generation1": {"const": True},
                },
            },
            "azure": {
                "type": "object",
                "required": ["subscription", "resource_group", "registry",
                             "storage_account", "results_container",
                             "container_apps_environment", "gpu_job",
                             "recovery_job"],
                "properties": {
                    "gpu_job": {"const": NS.GPU_JOB},
                    "recovery_job": {"const": NS.RECOVERY_JOB},
                    "container_apps_environment": {
                        "const": PREFIX.ACA_ENVIRONMENT},
                },
            },
            "prefix_proof": {
                "type": "object",
                "required": ["performed_in_vnet", "performed_in_acr",
                             "shared_canary_and_live_validator"],
                "properties": {
                    "performed_in_vnet": {"const": True},
                    "performed_in_acr": {"const": False},
                    "shared_canary_and_live_validator": {"const": True},
                },
            },
            "immutable_sources": {"type": "array", "minItems": 4,
                                  "items": blob},
            "delegated_scientific_modules": {"type": "array", "minItems": 4,
                                             "items": blob},
            "immutable_science": {
                "type": "object",
                "required": ["proved",
                             "science_is_unchanged_p0_r1_generation3"],
                "properties": {
                    "proved": {"const": True},
                    "science_is_unchanged_p0_r1_generation3": {"const": True},
                },
            },
            "generation1_terminal": {
                "type": "object",
                "required": ["closure_head", "image_digest", "state"],
                "properties": {
                    "closure_head": {
                        "const": GENERATION1_TERMINAL["closure_head"]},
                    "image_digest": {
                        "const": GENERATION1_TERMINAL["image_digest"]},
                    "state": {"const": "STOP_NO_MODEL_OPERATION"},
                },
            },
            "p0_r1_terminal": {
                "type": "object",
                "required": ["stop_commit", "state",
                             "replay_envelope_consumed", "launchable"],
                "properties": {
                    "stop_commit": {"const": P0_R1_TERMINAL["stop_commit"]},
                    "state": {"const": "STOP_NO_MODEL_OPERATION"},
                    "replay_envelope_consumed": {"const": True},
                    "launchable": {"const": False},
                },
            },
            "replay_envelope": {
                "type": "object",
                "required": ["consumed", "invocations", "rerunnable"],
                "properties": {
                    "consumed": {"const": False},
                    "invocations": {"const": 0},
                    "rerunnable": {"const": False},
                },
            },
            "caps": {
                "type": "object",
                "required": sorted(CAPS),
                "properties": {name: {"const": value}
                               for name, value in CAPS.items()},
            },
            "pre_replay_counters": {
                "type": "object",
                "required": sorted(PRE_REPLAY_COUNTERS),
                "properties": {name: {"const": 0}
                               for name in PRE_REPLAY_COUNTERS},
            },
            "standing_failures": {"type": "array", "minItems": 4,
                                  "items": string},
            "legal_state": {
                "type": "object",
                "required": sorted(LEGAL_STATE),
                "properties": {
                    "formal_execution_authorized": {"const": False},
                    "draft_v0_6_reviewed": {"const": False},
                    "draft_v0_6_frozen": {"const": False},
                    "evidence_ledger_tail": {"const": "EV-0016"},
                    "research_question_answered": {"const": False},
                },
            },
            "prohibitions": {
                "type": "object",
                "required": sorted(PROHIBITIONS),
                "properties": {name: {"const": True} for name in PROHIBITIONS},
            },
        },
    }


def validate(lock: dict, schema_document=None) -> dict:
    """Validate a lock with the v2 schema walker, imported not restated."""
    schema_document = schema_document if schema_document is not None \
        else schema()
    errors = V2._validate(lock, schema_document)  # noqa: SLF001 - shared walker
    if errors:
        raise LockDefect("; ".join(errors[:8]))
    payload = dict(lock)
    declared = (payload.get("self") or {}).get("sha256")
    recomputed = dict(payload)
    recomputed["self"] = dict(payload["self"])
    recomputed["self"]["sha256"] = None
    if declared != _sha256(canonical_bytes(recomputed)):
        raise LockDefect("the lock does not bind its own canonical bytes")
    NS.assert_disjoint_from_generation1([
        (lock.get("namespace") or {}).get("live_replay_attempt_id"),
        (lock.get("namespace") or {}).get("pilot_attempt_id"),
        (lock.get("namespace") or {}).get("live_blob_prefix"),
        (lock.get("namespace") or {}).get("pilot_blob_prefix"),
    ])
    if (lock.get("image") or {}).get("digest") == \
            GENERATION1_TERMINAL["image_digest"]:
        raise LockDefect(
            "the generation-2 image digest equals the generation-1 digest")
    return {
        "schema_version": "study3-p0-r2-execution-lock-validation-g2",
        "stage": STAGE,
        "generation": GENERATION,
        "outcome": "LOCK_VALID",
        "lock_sha256": declared,
        "errors": 0,
        "model_operations_performed": 0,
    }


def implementation_identity() -> dict:
    return {
        "schema_version": SCHEMA_VERSION,
        "module": "p0_r2_execution_lock_g2.py",
        "stage": STAGE,
        "generation": GENERATION,
        "lock_name": LOCK_NAME,
        "schema_name": SCHEMA_NAME,
        "terminal_state": TERMINAL_STATE,
        "authority_path": AUTHORITY_PATH,
        "task_path": TASK_PATH,
        "caps": dict(CAPS),
        "uses_v2_schema_walker": True,
        "caller_supplied_governance_allowlist": False,
        "model_operations_performed": 0,
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--identity", action="store_true")
    mode.add_argument("--schema", action="store_true")
    mode.add_argument("--build", action="store_true")
    mode.add_argument("--validate", action="store_true")
    parser.add_argument("--root")
    parser.add_argument("--inputs")
    parser.add_argument("--lock-file")
    parser.add_argument("--schema-file")
    parser.add_argument("--out")
    args = parser.parse_args(argv)

    if args.identity:
        print(json.dumps(implementation_identity(), indent=2, sort_keys=True))
        return 0

    try:
        if args.schema:
            document = schema()
        elif args.build:
            if not args.inputs:
                raise LockDefect("--build requires --inputs")
            inputs = json.loads(Path(args.inputs).read_bytes().decode("utf-8"))
            document = build(args.root, inputs=inputs)
        else:
            if not args.lock_file:
                raise LockDefect("--validate requires --lock-file")
            lock = json.loads(Path(args.lock_file).read_bytes().decode("utf-8"))
            schema_document = None
            if args.schema_file:
                schema_document = json.loads(
                    Path(args.schema_file).read_bytes().decode("utf-8"))
            document = validate(lock, schema_document)
    except (LockDefect, NS.NamespaceDefect, ValueError) as exc:
        print("P0_R2_G2_EXECUTION_LOCK_REFUSED=1 %s" % exc, file=sys.stderr)
        return 3

    payload = canonical_bytes(document)
    if args.out:
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.out).write_bytes(payload)
    print(payload.decode("utf-8"), end="")
    if args.validate:
        print("P0_R2_G2_EXECUTION_LOCK_VALID=1")
    return 0


if __name__ == "__main__":
    sys.exit(main())
