#!/usr/bin/env python3
"""Study 3 P0-R2 generation-2 hard-kill / open-admission recovery canary entry.

Authority:
``studies/study3/prompts/study3_p0_r2_generation2_successor_and_conditional_execution_authority.md``
section 7.4.

The canary implementation itself is the frozen generation-1 module, re-executed
byte-for-byte as a generation-2 instance. Only the namespace differs, so the
synthetic payload, the SIGKILL, the create-only journal, the byte-exact
comparison against independently regenerated bytes and the manifest-written-last
rule are all exactly the logic that already passed for generation 1.

This file exists because the canary parent spawns its own child as a separate
process by module path. Pointing that spawn at the frozen generation-1 file
would run the child in generation 1's namespace, where a generation-2 attempt id
is correctly refused. This entry point re-enters through the generation-2
instance instead, so parent and child share one namespace.

Model-free with respect to tokenizers, checkpoints, weights and GPUs: the
payload is synthetic and deterministic.
"""

from __future__ import annotations

import json
from pathlib import Path
import sys


P0_R2_DIR = Path(__file__).resolve().parent
if str(P0_R2_DIR) not in sys.path:
    sys.path.insert(0, str(P0_R2_DIR))

import p0_r2_namespace_g2 as NS  # noqa: E402


SCHEMA_VERSION = "study3-p0-r2-hard-kill-canary-g2"
STAGE = "STUDY3-P0-R2"
GENERATION = 2


def canary():
    return NS.hard_kill_canary()


def run(attempt_id: str, *, rows: int = 2) -> dict:
    """Run the parent side, spawning the child through this same entry point."""
    instance = canary()
    return instance.run_canary(attempt_id, rows=rows,
                               python=sys.executable, module=str(Path(__file__)))


def implementation_identity() -> dict:
    instance = canary()
    return {
        "schema_version": SCHEMA_VERSION,
        "module": "p0_r2_hard_kill_g2.py",
        "stage": STAGE,
        "generation": GENERATION,
        "delegates_to": "p0_r2_hard_kill_canary_v2.py",
        "delegated_bytes_unchanged": True,
        "attempt_prefix": instance.ATTEMPT_PREFIX,
        "recovery_manifest_name": instance.RECOVERY_MANIFEST_NAME,
        "real_sigkill": True,
        "simulated_exception_substituted": False,
        "waivable": False,
        "model_operations_performed": 0,
    }


def main(argv=None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv and argv[0] == "--identity":
        print(json.dumps(implementation_identity(), indent=2, sort_keys=True))
        return 0
    if argv and argv[0] == "--run":
        attempt = argv[argv.index("--attempt") + 1]
        rows = int(argv[argv.index("--rows") + 1]) if "--rows" in argv else 2
        out = argv[argv.index("--out") + 1] if "--out" in argv else None
        try:
            report = run(attempt, rows=rows)
        except Exception as exc:  # noqa: BLE001 - any failure is a stop
            print("P0_R2_G2_HARD_KILL_REFUSED=1 %s" % exc, file=sys.stderr)
            return 3
        payload = json.dumps(report, indent=2, sort_keys=True) + "\n"
        if out:
            Path(out).write_bytes(payload.encode("utf-8"))
        print(payload, end="")
        print("P0_R2_G2_HARD_KILL_OUTCOME=%s" % report.get("outcome"))
        return 0 if report.get("outcome") == "PASS" else 3
    # Every other mode, including --child and --recover-only, is the frozen
    # implementation's own, re-entered in the generation-2 namespace.
    return canary().main(argv)


if __name__ == "__main__":
    sys.exit(main())
